context("gdal utils")

#library(stars)

test_that('st_gdalinfo works', {
  fname = system.file("nc/avhrr-only-v2.19810901.nc", package = "stars")
  #st_gdalinfo(fname)

  st_get_subdatasets(fname)
})

#st_gdalinfo("NETCDF:avhrr-only-v2.19810901.nc:anom")

# gdalwarp -t_srs '+proj=utm +zone=11 +datum=WGS84' -overwrite NETCDF:avhrr-only-v2.19810901.nc:anom utm11.tif

#st_gdalwarp("NETCDF:avhrr-only-v2.19810901.nc:anom", "utm11x.tif")
#st_gdalwarp("NETCDF:avhrr-only-v2.19810901.nc:anom", "utm11.tif", c("-t_srs", "+proj=utm +zone=11 +datum=WGS84"))

#st_gdalrasterize("nc.gpkg", "nc.tif") # where nc.tif was generated by raster
#st_gdalrasterize("nc.tif", "nc.tif") # break
