# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPL_GetMetadata <- function(obj, domain_item, options) {
    .Call('stars_CPL_GetMetadata', PACKAGE = 'stars', obj, domain_item, options)
}

CPL_get_crs <- function(obj, options) {
    .Call('stars_CPL_get_crs', PACKAGE = 'stars', obj, options)
}

CPL_gdal_init <- function() {
    invisible(.Call('stars_CPL_gdal_init', PACKAGE = 'stars'))
}

CPL_gdal_cleanup_all <- function() {
    invisible(.Call('stars_CPL_gdal_cleanup_all', PACKAGE = 'stars'))
}

CPL_gdal_version <- function(what = "RELEASE_NAME") {
    .Call('stars_CPL_gdal_version', PACKAGE = 'stars', what)
}

CPL_proj_version <- function(b = FALSE) {
    .Call('stars_CPL_proj_version', PACKAGE = 'stars', b)
}

CPL_proj_is_valid <- function(proj4string) {
    .Call('stars_CPL_proj_is_valid', PACKAGE = 'stars', proj4string)
}

CPL_gdalinfo <- function(obj, options) {
    .Call('stars_CPL_gdalinfo', PACKAGE = 'stars', obj, options)
}

CPL_gdalwarp <- function(src, dst, options) {
    .Call('stars_CPL_gdalwarp', PACKAGE = 'stars', src, dst, options)
}

CPL_gdalrasterize <- function(src, dst, options) {
    .Call('stars_CPL_gdalrasterize', PACKAGE = 'stars', src, dst, options)
}

