# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPL_GetMetadata <- function(obj, domain_item, options) {
    .Call('_stars_CPL_GetMetadata', PACKAGE = 'stars', obj, domain_item, options)
}

CPL_get_crs <- function(obj, options) {
    .Call('_stars_CPL_get_crs', PACKAGE = 'stars', obj, options)
}

CPL_read_gdal <- function(fname, options, driver, read_data = TRUE) {
    .Call('_stars_CPL_read_gdal', PACKAGE = 'stars', fname, options, driver, read_data)
}

CPL_gdal_init <- function() {
    invisible(.Call('_stars_CPL_gdal_init', PACKAGE = 'stars'))
}

CPL_gdal_cleanup_all <- function() {
    invisible(.Call('_stars_CPL_gdal_cleanup_all', PACKAGE = 'stars'))
}

CPL_gdal_version <- function(what = "RELEASE_NAME") {
    .Call('_stars_CPL_gdal_version', PACKAGE = 'stars', what)
}

CPL_proj_version <- function(b = FALSE) {
    .Call('_stars_CPL_proj_version', PACKAGE = 'stars', b)
}

CPL_proj_is_valid <- function(proj4string) {
    .Call('_stars_CPL_proj_is_valid', PACKAGE = 'stars', proj4string)
}

CPL_xy2sfc <- function(cc, dim, to_points) {
    .Call('_stars_CPL_xy2sfc', PACKAGE = 'stars', cc, dim, to_points)
}

CPL_gdalinfo <- function(obj, options) {
    .Call('_stars_CPL_gdalinfo', PACKAGE = 'stars', obj, options)
}

CPL_gdalwarp <- function(src, dst, options) {
    .Call('_stars_CPL_gdalwarp', PACKAGE = 'stars', src, dst, options)
}

CPL_gdalrasterize <- function(src, dst, options) {
    .Call('_stars_CPL_gdalrasterize', PACKAGE = 'stars', src, dst, options)
}

CPL_gdaltranslate <- function(src, dst, options) {
    .Call('_stars_CPL_gdaltranslate', PACKAGE = 'stars', src, dst, options)
}

CPL_gdalvectortranslate <- function(src, dst, options) {
    .Call('_stars_CPL_gdalvectortranslate', PACKAGE = 'stars', src, dst, options)
}

CPL_gdalbuildvrt <- function(src, dst, options) {
    .Call('_stars_CPL_gdalbuildvrt', PACKAGE = 'stars', src, dst, options)
}

CPL_gdaldemprocessing <- function(src, dst, options, processing, colorfilename) {
    .Call('_stars_CPL_gdaldemprocessing', PACKAGE = 'stars', src, dst, options, processing, colorfilename)
}

CPL_gdalnearblack <- function(src, dst, options) {
    .Call('_stars_CPL_gdalnearblack', PACKAGE = 'stars', src, dst, options)
}

CPL_gdalgrid <- function(src, dst, options) {
    .Call('_stars_CPL_gdalgrid', PACKAGE = 'stars', src, dst, options)
}

